### ISSUE TITLE
A few suggestions...

### ISSUE THREAD

**Issue by GilbertMizrahi** [bigfanjs/react-titles#1]
First, this is a nice library. Thanks.

It would be nice to allow passing other parameters as props in the API, such as:
text1 color
text2 color

in Title10, there is another text1 color (when splitting the text
rect color and stroke
easing method (in addition to Power4)

**Comment by bigfanjs** [comment]
Hey @GilbertMizrahi, thank you and I appreciate you taking the time to give me suggestions to improve react-titles' component API. Sure I'll do what you have suggested and keep improving it. And also I am planning to add more advanced title components later. Thanks

**Comment by GilbertMizrahi** [comment]
Great. Thanks.
Another thing that could be interesting is to how link animations. For instance, run one and move it to the side and then run another one, etc. 
They can be combined with your other library react-explode.

**Comment by bigfanjs** [comment]
Beautiful! Thank you.
